### ISSUE TITLE
Step Sequencer from push?

### ISSUE THREAD

**Issue by Lucid-Network** [git-moss/OSC4Bitwig#32]
Can we get that? Not sure how that works in push actualy but would be cool to have such a mode.

**Comment by git-moss** [comment]
Yes, should be possible. I would need to add sending of playing notes and the position, also functions to set/delete notes, etc.
I think you should check first how you could implement a sequencer in Lemur and what you need before we start specifying an API.

**Comment by Lucid-Network** [comment]
ok, need to think about a good way. Until then i guess you can close here.

cheers!
