### ISSUE TITLE
communication problem

### ISSUE THREAD

**Issue by Suloo** [git-moss/OSC4Bitwig#34]
Hey,
there seems to be an issue with that latest files on GitHub. I do get an error message in the console log:
﻿﻿Wrapped com.bitwig.base.control_surface.ControlSurfaceException: Host is down (OSCWriter.js#127)

the stable version from your HP works fine.

**Comment by git-moss** [comment]
Looks like a legit error message: Are you sure that your target IP / port is configured correctly?
Works fine here.
