### ISSUE TITLE
Flush command?

### ISSUE THREAD

**Issue by teotigraphix** [git-moss/OSC4Bitwig#36]
Hey,

Before I go hacking, I looked through all the code and didn't see a way to flush and get a full refresh.

In my app it starts up, but I need a full refresh once the UI is drawn. Have you needed to do this? Or do I need to add a;

'writer.flush (true);'

For a command.

**Comment by git-moss** [comment]
Hi Mike,
I added the command for you: '/refresh'
Cheers!
