### ISSUE TITLE
please add pitchbend / modwheel

### ISSUE THREAD

**Issue by Suloo** [git-moss/OSC4Bitwig#41]
Hey Moss,

i would like to improve the piano in Lemur and would need a few messages here: 
- pitchbend
- modwheel
- breath
- expression
- gate
- aftertouch
- velocity

thanks a lot!
cheers

**Comment by git-moss** [comment]
Please test:
/vkb_midi/{Channel:0-16}/cc/{CC:0-127} {Value:0-127}
/vkb_midi/{Channel:0-16}/aftertouch/{Note:0-127} {Pressure:0-127}
/vkb_midi/{Channel:0-16}/pitchbend {Pitch:0-127 (No-Bend:64)}

**Comment by Suloo** [comment]
Cool, all is working nice expect of aftertouch it seems, getting this in the consol:

﻿﻿Can't find method com.bitwig.flt.control_surface.intention.sections.DirectNoteInput.sendRawMidiEvent(number,org.mozilla.javascript.Undefined,number). (OSCParser.js#1044)

**Comment by Suloo** [comment]
Regarding velocity i thought it might be possible to have a fader, wich sets the global velocity amount for all notes that are played. And/or depending on where the note objects get touched in Lemur, the velocity will be higher or lower. Do you think that might work?

**Comment by git-moss** [comment]
You forgot the note for which the aftertouch is sent, e.g.:
/vkb_midi/1/aftertouch/60 127

**Comment by Suloo** [comment]
ah ok, perfect

**Comment by git-moss** [comment]
/vkb_midi/velocity {0-127 (0 disables fixed velocity, 1-127 fixes the velocity to the value)}
