### ISSUE TITLE
please add mapping bank switches

### ISSUE THREAD

**Issue by Suloo** [git-moss/OSC4Bitwig#42]
Hey,

it would be cool if we could switch the parameter banks in:

- device/param
- device/common
- device/envelope
- device/modulation

cheers

**Comment by git-moss** [comment]
What do you mean? That's how they are named currently.

**Comment by Suloo** [comment]
Sorry, should have been more clear. What i mean is to be able to switch within the banks.
![sdsd](https://cloud.githubusercontent.com/assets/3390820/7215076/bf653f2c-e5c6-11e4-9015-7aa29fbc6350.jpg)

Like here, to switch between OSC1 - OSC2 - Mix/AMP etc.
Basically to switch to the next 8 parameters.

**Comment by Suloo** [comment]
Should have said "switching pages"

**Comment by git-moss** [comment]
/device/param/+ and /device/param/- isd already there.
The other ones only have 8 parameters and need no bank switching.
