### ISSUE TITLE
Please add Set as Primary

### ISSUE THREAD

**Issue by Suloo** [git-moss/OSC4Bitwig#43]
Hey,

is that already available from the API?
Like when you rightclick on a device you can set it as primary in that menu. 
Would be nice to have a message for that.

cheers

**Comment by git-moss** [comment]
In the API there is the function PrimaryDevice.switchToDevice. Its parameters might be a bit problematic. How would you intend to use the message and how should it be formed?

**Comment by Suloo** [comment]
I would first select a device with /device/+ or /device/- and then would like to have a button, i guess boolean, to set the selected device as primary device.

**Comment by git-moss** [comment]
That's not possible. If you look at the function you can only set the primary device to the FIRST, NEXT, PREVIOUS and LAST. 
We could do /primary/+ and /primary/- 
Would that be helpful?

**Comment by Suloo** [comment]
ok, yes that would work.

**Comment by git-moss** [comment]
That's actually already working since all /device messages also work for /primary :-)
