### ISSUE TITLE
Disable VU meter as Option?

### ISSUE THREAD

**Issue by ThomasHelzle** [git-moss/OSC4Bitwig#47]
Hey :-)
I currently try out OSC4Bitwig with Usine Hollyhock 2 (http://www.sensomusic.com/).
It so far works very well, but I would like to reduce clutter by disabling the VU meters. 
Would it be possible to have this as an option in the script preferences? I would guess that could also reduce bandwidth usage with weaker WIFI connections...?

Thanks!

Tom

**Comment by git-moss** [comment]
Hi Tom!
Sure could be done but I am not sure if this has really a big performance impact. Unless it is not a problem I would like to keep it as it is.
Cheers!

**Comment by csvance** [comment]
Moss, when I have been working on the Lemur side of the fork I did notice that the method that handles whether a value has been flushed or not was not working as intended. I am pretty sure its some sort of bug in Bitwig's javascript implementation when an object has too many keys.

I was able to work around it by implementing a TRIE system in my branch that cut down OSC traffic by close to 99%. However the drawback was increased CPU usage during polling on the Bitwig side. I am thinking maybe a fully observer event driven flushing method may be needed.

**Comment by ThomasHelzle** [comment]
Well, I guess I have to go hacking myself in that case. 

Usine has a kind of automatic OSC-detection and since the VUs fire all the time, no matter if anything is happening or not, I can't prevent it from receiving data I'm not interested in. (Think a noisy Midi Controller and Midi Learn).

What would I need to disable to prevent VUs from being observed at all without breaking anything else? I never want them. Ever ;-)

Cheers,

Tom

**Comment by git-moss** [comment]
Stop your engine I am adding other options, so I will add this as well :-)

**Comment by git-moss** [comment]
Done: /track/vu {0,1}

@csvance: You are right but that would require a fundamental change of the Bitwig concept of observers and their flush calls.

**Comment by ThomasHelzle** [comment]
Hm - not exactly what I'm after so I might dig into the code myself if I find the time.
So far I was unable to send OSC to Bitwig from Usine...  Still trying to find out what's wrong...
But thanks anyway. ;-)

**Comment by ThomasHelzle** [comment]
This is rather simple to do actually - I just deleted everything containing "VU" in the script :-)
I am happy to do that myself, so you don't need to bother with it.
