### ISSUE TITLE
Note Feedback VKB

### ISSUE THREAD

**Issue by Lucid-Network** [git-moss/OSC4Bitwig#48]
Hey,

it would be nice to have a feedback from the notes that are played, so i could use the message as an input in lemur in order to change the color of a key, when a note is played.

**Comment by git-moss** [comment]
Why don't you simply change the color for the pressed state?

**Comment by Lucid-Network** [comment]
I already did that, but for example, when i got a midi region in playback it would be nice to see the notes that are played. I mean, when you draw a midi note, to have a feedback about this.

**Comment by git-moss** [comment]
That would mean sending the notes of the currently selected and playing clip? That makes sense.

**Comment by Lucid-Network** [comment]
yes

**Comment by git-moss** [comment]
Looking at the Push4Bitwig code I thought it would make sense to support the same states (not just pressed). Also if we want to support scales later on it will be ready.

So now you will receive color values for all notes (0-127), I thought that makes it easier than status codes which you would need to replace.
You get different colors for root notes, scale notes, out-of-scale notes, pressed or sequence notes (in red if recording is enabled).

/vkb_midi/note/{0-127}/color RGB(r,g,b)

**Comment by Lucid-Network** [comment]
Awesome! thx :)

**Comment by Lucid-Network** [comment]
https://www.dropbox.com/s/3fy54mpeirk4tl8/2015-04-26%2020.58.51.mp4?dl=0

looks funny but kinda cool.. :dancer: 

Vegas Mode :D
https://www.dropbox.com/s/3fy54mpeirk4tl8/2015-04-26%2020.58.51.mp4?dl=0

**Comment by Lucid-Network** [comment]
Ok, works now solid..

**Comment by git-moss** [comment]
Funky :-)
