### ISSUE TITLE
Please Add Name feedback of selected track

### ISSUE THREAD

**Issue by Lucid-Network** [git-moss/OSC4Bitwig#50]
Would be great to have /track/selected/name  for the device page.

cheers

**Comment by git-moss** [comment]
Should the be the selected track in the track bank (instrument and audio trracks) or the cursor track (instr, audio, effect or master)?

**Comment by Lucid-Network** [comment]
hm yea, good question. With the cursor track we would have more options. Still could be confusing if one has selected a track first in the mixer panel. hm, anyway, lets go with the cursor one, so people could also access devices on the effects and master + audio audio and intruments.

**Comment by Lucid-Network** [comment]
Infact it would be cool if the trackbank on the mixer page could also access the effect tracks.

**Comment by Lucid-Network** [comment]
Also maybe better to wait for 1.2 and see how that could then.

**Comment by git-moss** [comment]
I was thinking now quite a bit about this and track banks. I decided now to implement it as with the Push script which means:
- the Audio/Instrument OR effect track bank is active. You can toggle them now with "/track/toggleBank"
- /track/selected/* sends now all attributes of the selected track of the active track bank. This implies that e.g. if the effect track bank is active and an audio track is selected the /track/selected values are empty.

The alternative was to send the information about both banks in parallel. This would have implied to duplicate the devices and selected track info too. Which I thought was too much.

By doing this I noticed that the attributes "exists" and "canHoldNotes" were missing, they are added now.

The changes are not yet on GitHub. Currently, there seems to be a problem with checking in.

**Comment by git-moss** [comment]
Checked in now.

**Comment by Lucid-Network** [comment]
ok, so i need to create two seperated faderbanks, one for audio/instrument and one for fx wich automatically change over depending on the toggled trackbank, nice!

Can we have a feedback of the selected bank? I mean, when i select an audio track, i would like to have the toggle state in lemur to automatically change as well.
