### ISSUE TITLE
Autoselect first track of a bank

### ISSUE THREAD

**Issue by Lucid-Network** [git-moss/OSC4Bitwig#53]
Hey,

when toggling the track bank, it would be helpful to have the first track of that bank bein autoselected.
Especially because otherwise now with /track/selected/name nothing shows up until i trigger /track/+ or /track/-

Actualy it remembers the last track that is selected, but when switching the bank, to effects for example, its still the selected track of the audio/instrument wich is showing up.

**Comment by git-moss** [comment]
Done.
