### ISSUE TITLE
Midi-Clock?

### ISSUE THREAD

**Issue by Lucid-Network** [git-moss/OSC4Bitwig#55]
Hey,

it seems that lemur is only able to receive a clock via midi. The manual states a midi-clocks variable wich can work with incoming midi clock signals. There is not stated any info about receiving an OSC clock. So would it be possible, that you could send out a midi clock from the script. Working on a simple step sequencer layout, wich would requiere proper syncing.

cheers

**Comment by git-moss** [comment]
Both ways it is currently not possible to get a proper sync signal inside the Bitwig scripts (I made a lot of attempts in the past).
