### ISSUE TITLE
Can't expand the settings by pressing the gear button.

### ISSUE THREAD

**Issue by dal00** [git-moss/OSC4Bitwig#57]
I'm running Bitwig 1.1.8 on Ubuntu 15.04 with the latest git code from this repo. I can't expand the settings by pressing the cog/gear and also it is grayed out. It works in the SLMK2 script.

**Comment by git-moss** [comment]
You need to assign a midi device or the script won't Start. Best is to use a virtual device. The device is necessary to send midi notes and CC to bitwig.
