### ISSUE TITLE
1.2 features?

### ISSUE THREAD

**Issue by Lucid-Network** [git-moss/OSC4Bitwig#58]
Hey Moss,

how do we go about 1.2 features? Could you provide what the Api has made it into push, so we could work it out? Or shall i request single stuff? Got the Beta available, so work could start.

cheers

**Comment by git-moss** [comment]
Does not make much sense with Beta 1. As you might have noticed I released a preview of Push4Bitwig but it is full of bugs (the new browser) and not quite usable. Let's wait for the next iteration.
