### ISSUE TITLE
Device name issue

### ISSUE THREAD

**Issue by Lucid-Network** [git-moss/OSC4Bitwig#59]
Got a problem in Lemur with:

/device/name
/primary/name

On the device page in Lemur, i got the field with the device names in floating windows. When i freshly copy those messages in there, it shows them fine. But after a while (cannot exactly say when) it doesn't react on the message anymore. 

However, on the preset selection page it always reacts. Could it be an issue with receiving the message twice? Could also be Lemur that causes the issue, don't know yet.

Any idea? Anything special about those messages in the code?

cheers

**Comment by git-moss** [comment]
No idea what I could do about it. Also if it is working fine on the preset selection page the messages are sent. Try reporting to the Lemur guys.
