### ISSUE TITLE
Doesn't send a length-prefixed packet

### ISSUE THREAD

**Issue by alandrees** [git-moss/OSC4Bitwig#60]
Some OSC libraries require TCP-transport OSC streams to be length-prefixed packets, neither the bundles nor the raw osc packets prepend this in the OSCMessage library.

Under the 'Atomicity' subheading:
http://opensoundcontrol.org/files/osc-best-practices-final.pdf

**Comment by git-moss** [comment]
Thanks for pointing me to the paper, it was an interesting read.
I guess you are referring to section 4.2? This section talks about running OSC on TCP/IP but the Bitwig implementation uses UDP, which is discussed in section 4.1 and 4.2 does not apply here.
With which library does that problem exist?

**Comment by alandrees** [comment]
In my case, I'm just using the OSCMessage.js object and sending them via TCP, as I didn't need any more of the logic for this use-case.

**Comment by alandrees** [comment]
here is how I'm using it:
https://gist.github.com/alandrees/9c49be9ce570123b06f4

**Comment by git-moss** [comment]
Ah, I see. Then I suggest to better create a fork.
