### ISSUE TITLE
FR: some more usefull messages to complete.

### ISSUE THREAD

**Issue by zengels** [git-moss/OSC4Bitwig#64]
Hi Hi mr Moßgraber ! 

would it be possible to include this messages that could be send by the script to the lemur to complete a bi-directionnal communication ?

/panel/noteEditor 
/panel/automationEditor 
/panel/devices 
/panel/mixer 

Thanks Mr !
have a good night ! ;)

**Comment by git-moss** [comment]
Sorry, it's not in the API.

**Comment by zengels** [comment]
Hi mr Moßgraber !
Thanks ! it's been 3 days i put objects in the github... i just see that nothing sync...
i try to figure out why... but the purpose of my message is about putting in your script the name of scenes. i  didn't push that request here yet ;)
it's done !
Many thanks again for your work !

**Comment by Lucid-Network** [comment]
better open a new issue for that ;)
