### ISSUE TITLE
Hi Moss!!

### ISSUE THREAD

**Issue by zengels** [git-moss/OSC4Bitwig#66]
Hi Moss! 
how are you ! hope you had holidays! i came back beginning september and get back to work with my band project and Lemur for Bitwig one. 
then i have one request ;)
i need the name of Sends independently if possible . like '/send/{1-8}/name' .something like that ;)
thanks!
i managed to add the lemur for bitwig script to add function you added for the 1.2 version of bitwig .
i add them one by . finishing the part of the template for this function and add a new one ;)
i need that to continue the template, before Caroll update the script officially (and he will do that a lot better than me... i do it only for continuing)  ;)
do you want me to send you the template on your email ? if yes. give me your email ;) you will then test it . 
have a nice day !

**Comment by git-moss** [comment]
Hi Zengels,
I can add the Send name but you can already do:
/track/1/send/{1-8}/name
Since they are always the same for all track you can just use the 1st one.
Regarding looking at the templete I am quite busy currently and prefer to take a look when its finished :-)
Cheers!
