### ISSUE TITLE
Hi Moss!!

### ISSUE THREAD

**Issue by zengels** [git-moss/OSC4Bitwig#67]
Thanks for Sends name ! it worked perfectly!
now . i managed to add the Drumpad name (layers) to the lemur script. but it works only for 8 drumpads. is it normal or perhaps i made something wrong. if not, could it be possible to have name of 16 pad ?
thanks Moss !

**Comment by zengels** [comment]
Hi again great guy!
just to say that i managed to make the lemur script sends the 16 drumpads names of a page...certainly with bugs (i change 'this.numDeviceLayers' in 'CursorDeviceProxy'  from 8 to16 (...such names!! ;)...may have other concequences...lol ) but it seems to work for drum pad and i can make the drumpad part for the lemur template now until the official lemur script from Caroll . have a nice evening  ! ;) ...
PS : may i have missed something ? the script (the osc4witwig one) sent already the 16 names (i managed to send only the first 8 per pages....)

**Comment by git-moss** [comment]
Currently, some parameters can not be set in the CursorDeviceProxy, I put it on my TODO list.
BTW, please add a meaningful title when you create a new request or bug issue.
