### ISSUE TITLE
punch-in punch-out received but not sent

### ISSUE THREAD

**Issue by zengels** [git-moss/OSC4Bitwig#69]
Hi Moßgraber !
first sorry for the 'meaningful title' i will care more about it now .
i try to make the '/punchIn' '/punchOut' fonction work correctly .
i receive them from the script to the lemur correctly but i didn't managed to make the script receive them .
on the lemur template i receive the current state for both but i can't change the state from my template...
perhaps i didn't send the good message?
is '/punchIn' with the value 1 correct (same for '/punchOut')?
i tried to understand why it does not work on the OSCParser and in the TransportProxy...i didn't managed to understand . all seems to be good.
thanks for reading !

**Comment by git-moss** [comment]
Since it can only toggle it has no value: "/punchIn"

**Comment by zengels** [comment]
Thanks for this precision !
i managed to make it work. 
As lemur could not send empty value i changed the OCSParser script for the lemur script from :
'
case 'punchIn':
            if (value == null)
                this.transport.togglePunchIn ();
            break;
'
to
'
case 'punchIn':
            if (value == null || value > 0)
                this.transport.togglePunchIn ();
            break;
'

so that i can send the value '1' to toggle the punch function ! ;) 
thanks a lot for your help ! ;)

**Comment by zengels** [comment]
have a niCe day ! ;)
