### ISSUE TITLE
unique Device id

### ISSUE THREAD

**Issue by zengels** [git-moss/OSC4Bitwig#70]
Hi Moß!!
how is the day today! cold in Paris but hot under my finger! ;)
i would like to know if it is possible to have a unique Id for each existing device (native or no native) in a session ?

and ... is it possible to have , in the same time, unique reserved id for native plugins that are always the same no matter the sessions ??

the name is not enough if you want to distinguish each device .
hope you will have a nice week-end ! see you later Moß !

**Comment by git-moss** [comment]
Yes, would be nice to have (also searching for a specific device on a track) but it is currently not possible. It is already on Bitwigs very long wishlist.

**Comment by zengels** [comment]
ok, i will do what i want with device name at the moment ;)
thanks for your answer ! ;)
