### ISSUE TITLE
Group fold/unfold

### ISSUE THREAD

**Issue by Lucid-Network** [git-moss/OSC4Bitwig#71]
Hey

sorry if i missed smth obvious, but do we have 

/track/{1-8}/fold
/track/{1-8}/unfold

or  /track/{1-8}/fold  (1,0)
while 1 = fold and 0 = unfold

to fold or unfold the groups content?

the trackbank then should consider it as well and jump into it or see the unfolded tracks as part of the trackbank, not sure what makes more sense right now.

cheers

**Comment by git-moss** [comment]
Sorry, not possible.

**Comment by Lucid-Network** [comment]
oh, thats a pitty, such a common usecase not supported in the API? 
I'll make a FR then i guess..
