### ISSUE TITLE
/track/{1-8}/isAudio (isInstrument etc..)

### ISSUE THREAD

**Issue by Lucid-Network** [git-moss/OSC4Bitwig#72]
Hi,

i would like to create an icon wich gives me information about the track flavour.

there is /track/{1-8}/isGroup

it would be nice to have:
/track/{1-8}/isAudio
/track/{1-8}/isHybrid
/track/{1-8}/isInstrument
/track/{1-8}/isFX

**Comment by git-moss** [comment]
The API sends a track type like "instrument", "audio", etc. Would that also be a solution?

**Comment by Lucid-Network** [comment]
i think so yes

**Comment by git-moss** [comment]
There is now .../type for all tracks.
