### ISSUE TITLE
Bitwig crash when deleting group tracks

### ISSUE THREAD

**Issue by Lucid-Network** [git-moss/OSC4Bitwig#75]
Hey,

not sure if it is something that Bitwig would need to fix, but just to let you know, in the new 1.3.8 RC1 Bitwig crashes completely when deleting a group track while OSC4Bitwig is loaded in preferences. This is on Os X 10.11.3

**Comment by git-moss** [comment]
Seems they broke something in 1.3.8. This happens with all scripts. Since I can't do anything about it I will close this.
