### ISSUE TITLE
TypeError: Cannot find function

### ISSUE THREAD

**Issue by Lucid-Network** [git-moss/OSC4Bitwig#76]
﻿﻿﻿Hey Moss,

after initialization i get the following error in the bitwig consol:

![bildschirmfoto 2016-06-05 um 10 09 38](https://cloud.githubusercontent.com/assets/3390820/15804358/dcf11572-2b05-11e6-96b2-4ff0054c99ca.png)

Is that something to worry about?
Edit: yes, it seems to break bidirectional communication with lemur

**Comment by git-moss** [comment]
Fixed. Thanks for reporting!
