### ISSUE TITLE
browser -> messages are mixed up

### ISSUE THREAD

**Issue by Lucid-Network** [git-moss/OSC4Bitwig#81]
Ok, so there are a few issues with the naming and ordering. I will try to list them now:

1. /browser/filter/1/{+,-} -> is filter "Everything" but /browser/filter/1/item/{1-16}/name shows "All preset location"

2. /browser/filter/4/{+,-) -> is filter column "All Devices" but should be "Any category". Also /browser/filter/4/item/{1-16}/name shows the list of "Any Tags"

3. /browser/filter/5/{+,-} -> is filter column "Any category" but should be "Any creator". Also /browser/filter/5/item/{1-16}/name shows the list of the column "All devices" 

4. /browser/filter/2/{+,-} -> is filter column "Any creator" but should be "All preset locations". Also /browser/filter/2/item/{1-16}/name shows the list of column "Everything"

5. /browser/filter/6/{+,-} -> doesn't have an effect in the browser and it should be column "Any tags". Also /browser/filter/6/item/{1-16}/name shows the list of "Any category"

6. /browser/filter/3/{+,-} -> is filter column "Any tags" but should be "All devices". Also /browser/filter/3/item/{1-16}/name shows the list of "Any creator"

Preset selection and list of names are working fine. Didn't check the other messages like exist or isSelected yet.

**Comment by git-moss** [comment]
See the index bugfix and the updated Wiki information which index belongs to which column.
