### ISSUE TITLE
/browser/filter/{1-6}/{+,-} and /browser/preset/{+,-}

### ISSUE THREAD

**Issue by Lucid-Network** [git-moss/OSC4Bitwig#84]
Hey,

when i trigger those, the selection always jumps in steps of two. Like from 1 to 3 to 5.
Is that something from the script or is it on my side? Couldn't find a solution yet and those buttons are setup the same way as others.

**Comment by git-moss** [comment]
I guess your button press triggers it twice (on down and on up)?

**Comment by Lucid-Network** [comment]
yea also thought so, gonna look into it again.

**Comment by Lucid-Network** [comment]
works again now, sometimes there are strange hickups like this. Also with visual updating the info in the app. But i guess there is not much to do about.
