### ISSUE TITLE
Organising the browser items like a trackbank?

### ISSUE THREAD

**Issue by Lucid-Network** [git-moss/OSC4Bitwig#85]
Would it be possible to do that? Because now i can only display 6 items, due to limited screenspace. When i want to select the 7th the cursor in Bitwig moves fine, but i can still only see the first 6 items in lemur.

 I think it would be great if a whole bank could be monitored and displayed, so i can switch the items also in lemur. Just like /track/bank/{+,-}

**Comment by git-moss** [comment]
Couldn't you do that with scripting in the client?

**Comment by Lucid-Network** [comment]
I don't know myself, but i'll ask in the community.

**Comment by Lucid-Network** [comment]
I doubt anyone can help me with that and i'm not able to do it. Could you add that maybe just for the presets? Or would that eat too much performance?

**Comment by git-moss** [comment]
Hi, I had a go at that yesterday but gave up. To keep the window of the list in sync with the selection is horribly complicated and eats a lot of power. Sorry, you need to find a solution on the client.
